//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGamesNET.Resources.Games.Checkers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class CheckersSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CheckersSettings defaultInstance = ((CheckersSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CheckersSettings())));
        
        public static CheckersSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color EatableCheckerColor {
            get {
                return ((global::System.Drawing.Color)(this["EatableCheckerColor"]));
            }
            set {
                this["EatableCheckerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color AvailableMoveColor {
            get {
                return ((global::System.Drawing.Color)(this["AvailableMoveColor"]));
            }
            set {
                this["AvailableMoveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LawnGreen")]
        public global::System.Drawing.Color SelectedPieceColor {
            get {
                return ((global::System.Drawing.Color)(this["SelectedPieceColor"]));
            }
            set {
                this["SelectedPieceColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color ForcedEaterColor {
            get {
                return ((global::System.Drawing.Color)(this["ForcedEaterColor"]));
            }
            set {
                this["ForcedEaterColor"] = value;
            }
        }
    }
}
